include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:

analyzer:
  errors:
  
    avoid_positional_boolean_parameters: ignore
    sort_pub_dependencies: ignore
    avoid_returning_this: ignore

  exclude:
    - lib/l10n/**
    - lib/**.g.dart