name: safegem
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # intl
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

  # routing
  go_router: 14.2.0

  # style
  cupertino_icons: 1.0.8
  avatar_glow: 3.0.1
  flutter_animate: 4.5.0
  font_awesome_flutter: 10.7.0
  modal_bottom_sheet: 3.0.0

  # business logic
  speech_to_text: 6.6.2
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  hydrated_bloc: 9.1.5
  url_launcher: 6.3.0

  # native
  path_provider: 2.1.3
  geolocator: 12.0.0
  connectivity_plus: 6.0.3

  # di
  get_it: 7.7.0
  injectable: 2.4.2

  # ai
  google_generative_ai: 0.4.3

  # models
  dartz: 0.10.1
  equatable: 2.0.5
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lint
  very_good_analysis: 5.1.0

  # code gen
  injectable_generator: 2.6.1
  build_runner: 2.4.11
  json_serializable: 6.8.0

flutter:
  uses-material-design: true
